### PR TITLE
Upgrade to use golang 1.16

### PR DESCRIPTION
**Pull request by Fedosin**
This commit sets the minimal golang version for the project to 1.16.

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
this looks fine to me, do we need to add the `UPSTREAM: <carry>: ` language to the commit log or will the rebase bot just do the proper thing?

**Comment by Fedosin** [comment]
This is not an upstream fork as I see... Since we don't have a repository to sync with, we don't need the tag.

**Comment by elmiko** [comment]
excellent point, i have to admit i forgot which repo we were on :joy:

/approve
/lgtm

**Pull request merged**
