### PR TITLE
Machine api v0.4.0

### PR DESCRIPTION
**Pull request by menglingwei**
alibabacloud machine-api

### CODE REVIEW

**Comment by elmiko** [comment]
you can drop the OWNERS file commit from this, i have opened #2 to add it.

**Comment by menglingwei** [comment]
I removed the OWNERS files

**Comment by elmiko** [comment]
thanks @menglingwei , i think we should probably merge this as is and then start running the ci against it to see if there are any changes needed.
/lgtm
cc @JoelSpeed

**Comment by JoelSpeed** [comment]
Since we seem to just be copying the alibaba version of this repo, is there any reason not to have forked the repo rather than doing this PR? If we were to fork, we would retain the history right?

**Comment by elmiko** [comment]
> Since we seem to just be copying the alibaba version of this repo, is there any reason not to have forked the repo rather than doing this PR? If we were to fork, we would retain the history right?

good question, i had wondered about that but in discussion about setup with @menglingwei this was the methodology we discussed (create new branch, then create a pr).

i believe you are correct about the history aspect of the fork.

**Comment by menglingwei** [comment]
@elmiko  @JoelSpeed  You're referring to the repo fork from Alibaba？

**Comment by elmiko** [comment]
@menglingwei correct. Joel is saying that we could have made the request to create this repository use a fork from the https://github.com/AliyunContainerService/cluster-api-provider-alibabacloud repository. then we would keep the history and the repo would be populated from there.

if that sounds better, i can investigate if we can do that.

**Comment by menglingwei** [comment]
> @menglingwei correct. Joel is saying that we could have made the request to create this repository use a fork from the https://github.com/AliyunContainerService/cluster-api-provider-alibabacloud repository. then we would keep the history and the repo would be populated from there.
> 
> if that sounds better, i can investigate if we can do that.

@elmiko   I think it's doable. You can fork from https://github.com/AliyunContainerService/cluster-api-provider-alibabacloud . 
If there is any problem, you  can assign issues  to me

**Comment by menglingwei** [comment]
@elmiko But in our(alibaba) repo, the master branch is too old. so you can use branch machine-api-v0.4.1.
Next, we'll merge the branch ”machine-api-v0.4.1" into the master branch.

**Comment by elmiko** [comment]
thanks @menglingwei , i will do some investigation to see how we can set this up. we _might_ need to delete and remake this repo, but i will update you before we do anything.

**Comment by elmiko** [comment]
@menglingwei , @JoelSpeed and i are discussing the options for bringing the code over here and we have a couple questions. as we see it, there are 3 options we could do:

1. merge this pr
2. recreate this repo as a fork from the machine-api-v0.4.1 branch of the aliyuncontainerservice repo
3. push the machine-api-v0.4.1 branch from the aliyuncontainerservice repo into this repo

2 and 3 allow us to keep the history of that branch (39 commits).

this had led us to ask a couple questions:

1. do you plan to continue working on the aliyuncontainerservice repo? (ie is there value in making this a fork of that repo)
2. assuming yes to 1, do you plan to promote patches from that repo to this one?

if the answer is no, then i think we can just merge this patch and keep working here. but if you would like to preserve some sort of fork between the two, then we should make sure that the histories are the same.

i don't have a personal preference. the history on the aliyuncontainerservice repo is not that long, so if the plan is to continue work here then i think we should just merge this. but i want to make sure we explore the option of preserving the history, if needed.

**Comment by menglingwei** [comment]
> @menglingwei , @JoelSpeed and i are discussing the options for bringing the code over here and we have a couple questions. as we see it, there are 3 options we could do:
> 
> 1. merge this pr
> 2. recreate this repo as a fork from the machine-api-v0.4.1 branch of the aliyuncontainerservice repo
> 3. push the machine-api-v0.4.1 branch from the aliyuncontainerservice repo into this repo
> 
> 2 and 3 allow us to keep the history of that branch (39 commits).
> 
> this had led us to ask a couple questions:
> 
> 1. do you plan to continue working on the aliyuncontainerservice repo? (ie is there value in making this a fork of that repo)
> 2. assuming yes to 1, do you plan to promote patches from that repo to this one?
> 
> if the answer is no, then i think we can just merge this patch and keep working here. but if you would like to preserve some sort of fork between the two, then we should make sure that the histories are the same.
> 
> i don't have a personal preference. the history on the aliyuncontainerservice repo is not that long, so if the plan is to continue work here then i think we should just merge this. but i want to make sure we explore the option of preserving the history, if needed.

@elmiko We will always update and maintain aliyunContainerService repo. So you can fork from this repo.

**Comment by elmiko** [comment]
thanks @menglingwei , i will discuss with Joel and get this repo configured properly.

**Comment by elmiko** [comment]
talked with @JoelSpeed, he is going to bring the branch over and then propose PR to merge it. this way we can preserve the history from the AliyunContainerService repo.

**Comment by menglingwei** [comment]
@elmiko @JoelSpeed Thank you guys. Let's move on to the next step.

**Comment by elmiko** [comment]
@menglingwei just wanted to keep you updated on the progress. Joel has brought the branches over here, but there is a little cleaning that is needed before we merge. there are some binary artifacts checked in, and i think there might have bee a slight divergence that he is investigating.

we should have this sorted out in the next day or two =)

**Comment by menglingwei** [comment]
> @menglingwei just wanted to keep you updated on the progress. Joel has brought the branches over here, but there is a little cleaning that is needed before we merge. there are some binary artifacts checked in, and i think there might have bee a slight divergence that he is investigating.
> 
> we should have this sorted out in the next day or two =)

Good job!

**Comment by JoelSpeed** [comment]
I've pushed this branch https://github.com/openshift/cluster-api-provider-alibaba/tree/machine-api-v0.4.1-no-bin which is the same as the Alibaba branch, except I've rewritten the history to remove all traces of the `bin` directory. Adding it to the `.gitingore` quite early on.

It's not common practice to check built binaries into Git repos as the large artifact sizes makes it take a long time to push/pull the updates and, they can normally be rebuilt easily once the source code has been pulled.

I would recommend that you reset the aliyun fork to match this branch, then we can merge the branch into this repo too, and continue from there with both forks approximately in sync. Let me know if you have any further questions about this suggestion

**Comment by menglingwei** [comment]
Ok. Let me update that

**Comment by kwoodson** [comment]
@menglingwei What's the status of removing the bin directory?

**Comment by elmiko** [comment]
@kwoodson Joel has a branch setup here where he has removed the bins, i think he is just doing a little final cleanup.

https://github.com/openshift/cluster-api-provider-alibaba/tree/machine-api-v0.4.1-no-bin

**Comment by menglingwei** [comment]
@kwoodson I also made an update on the Alibaba repo. I have removed the bins. cherry-pick from https://github.com/openshift/cluster-api-provider-alibaba/tree/machine-api-v0.4.1-no-bin. But I'm not sure that's the best way.

**Comment by kwoodson** [comment]
Thanks @menglingwei! Let's see what @elmiko and @JoelSpeed say.

**Comment by JoelSpeed** [comment]
My concern with https://github.com/openshift/cluster-api-provider-alibaba/pull/1/commits/1697c637e27caa6189734da29fb2e51fb4b4cf50 is that this means that the binaries are still in the git tree. Therefore, when I clone this repo, I have to pull down all the different versions of the binary that were checked in through the 15 or so commits that included the bin dir.

Looking at my local copy of this repo, this means that my `.git` folder is `443M`, where an equivalent repository for another provider that has been going for a lot longer is around `40M`. 

By rewriting the binaries out of the history like I have done, once merged and the old branches are deleted, if you were to remove and redownload your copy of the repository, it should be much much smaller on disk.

**Comment by menglingwei** [comment]
@JoelSpeed I see. How do you rewrite history? Can you tell me how? I'll do it again. Thank you

**Comment by menglingwei** [comment]
@JoelSpeed I used cherry-pick from your branch. But maybe I didn't do it right, so it doesn't seem to work as expected

**Comment by JoelSpeed** [comment]
So this is what I did in https://github.com/openshift/cluster-api-provider-alibaba/tree/machine-api-v0.4.1-no-bin, it's quite a complicated procedure.

The upshot of it is to find the last commit that didn't include the binary files, say `abcd1234`, then you `git rebase -i abcd1234`. From here you will have a list of commits and they will all say `pick` at the front. I then changed these to edit, went through each commit and make sure the binary files aren't preset, eg `rm -rf bin; git add .; git commit --amend`.

I would recommend you checkout the branch you have, make sure you have our repo configured as an upstream, then `git fetch openshift; git reset --hard openshift/machine-api-v0.4.1-no-bin`. This should make the two branches match. Once you've done this you will need to force push, so please make sure you review the changes before you force push. You may want to make a backup branch just in case this goes wrong, then you can reset again to that later

**Comment by menglingwei** [comment]
@JoelSpeed  Thank you. Let me hava a try.

**Comment by menglingwei** [comment]
@JoelSpeed  I have another question. Which branch are you using now for CI？

**Comment by menglingwei** [comment]
I do it in my github rep https://github.com/menglingwei/cluster-api-provider-alibaba/commits/machine-api-v0.4.0 ,but it didn't seems well. @JoelSpeed

**Comment by JoelSpeed** [comment]
I don't think we have any CI set up right now, could you show me where we are seeing failures please?

**Comment by JoelSpeed** [comment]
Looking at the history, I think we should be able to drop https://github.com/menglingwei/cluster-api-provider-alibaba/commit/1697c637e27caa6189734da29fb2e51fb4b4cf50, I'm surprised it wasn't already as it should have been a no-op commit

**Comment by elmiko** [comment]
on the topic of CI, i have this PR setup to enable the basic unit tests on this repo when we are ready. https://github.com/openshift/release/pull/20668

**Comment by menglingwei** [comment]
> I don't think we have any CI set up right now, could you show me where we are seeing failures please?

it's not failures. I found in my rep submitted on https://github.com/menglingwei/cluster-api-provider-alibaba/tree/machine-api-v0.4.0 and your submission (https://github.com/openshift/cluster-api-provider-alibaba/tree/machine-api-v0.4.1-no-bin) is different.  Therefore, I think my handling should be something not quite right. But I don't know where it happened

**Comment by JoelSpeed** [comment]
Do you know what commands you ran to create your branch/to reset it to match mine?

**Comment by menglingwei** [comment]
> Do you know what commands you ran to create your branch/to reset it to match mine?
1. git remote add openshift  https://github.com/openshift/cluster-api-provider-alibaba
2. git fetch openshift
3. git reset --hard openshift/machine-api-v0.4.1-no-bin

And then ,I resolved the code conflict. and commited it

**Comment by JoelSpeed** [comment]
That sounds correct as far as I can tell. I'm sorry I'm not understanding what the issue exactly is, would you be able to spell out exactly what differences/problems you're seeing?

**Comment by menglingwei** [comment]
> That sounds correct as far as I can tell. I'm sorry I'm not understanding what the issue exactly is, would you be able to spell out exactly what differences/problems you're seeing?

This is my commit history https://github.com/menglingwei/cluster-api-provider-alibaba/commits/machine-api-v0.4.0

This is yours https://github.com/openshift/cluster-api-provider-alibaba/commits/machine-api-v0.4.1-no-bin

I found  commit history havs a little different. So I think maybe  I'm not doing it right.

**Comment by JoelSpeed** [comment]
Got it! Ok, I see the differences, I think your branch is ok though, no issue regarding the reset :)

I would suggest dropping this https://github.com/menglingwei/cluster-api-provider-alibaba/commit/1697c637e27caa6189734da29fb2e51fb4b4cf50, otherwise I think history wise we are all good and things should be resolved regarding the binaries

**Comment by menglingwei** [comment]
Ok. Thank you.I'm going to try to drop the commit  [menglingwei@1697c63](https://github.com/menglingwei/cluster-api-provider-alibaba/commit/1697c637e27caa6189734da29fb2e51fb4b4cf50)

**Comment by kwoodson** [comment]
@menglingwei Were you able to drop the commit? Please let us know if we can assist. Thanks!

**Comment by kwoodson** [comment]
@menglingwei @JoelSpeed I attempted working with the no-bin branch and ran into a few issues.

I attempted to `make generate` and saw that the generated files need to be updated:
```
make generate
podman run --rm -e CGO_ENABLED=0 -e GOARCH=amd64 -e GOOS=linux -v "/home/kwoodson/go/src/github.com/openshift/cluster-api-provider-alibaba":/go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud:Z -w /go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud openshift/origin-release:golang-1.15 go generate ./pkg/... ./cmd/...
podman run --rm -e CGO_ENABLED=0 -e GOARCH=amd64 -e GOOS=linux -v "/home/kwoodson/go/src/github.com/openshift/cluster-api-provider-alibaba":/go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud:Z -w /go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud openshift/origin-release:golang-1.15 hack/goimports.sh .
hack/verify-diff.sh
diff --git a/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go b/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go
index b3a352a2..38d9670b 100644
--- a/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go
+++ b/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go
@@ -21,7 +21,7 @@ limitations under the License.
 package v1beta1
 
 import (
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/runtime"
 )
 
make: *** [Makefile:135: goimports] Error 1
```

@menglingwei Can you verify that the `make build` and other scripts produce the binaries? I was able to build with `podman build . `.

**Comment by menglingwei** [comment]
> @menglingwei @JoelSpeed I attempted working with the no-bin branch and ran into a few issues.
> 
> I attempted to `make generate` and saw that the generated files need to be updated:
> 
> ```
> make generate
> podman run --rm -e CGO_ENABLED=0 -e GOARCH=amd64 -e GOOS=linux -v "/home/kwoodson/go/src/github.com/openshift/cluster-api-provider-alibaba":/go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud:Z -w /go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud openshift/origin-release:golang-1.15 go generate ./pkg/... ./cmd/...
> podman run --rm -e CGO_ENABLED=0 -e GOARCH=amd64 -e GOOS=linux -v "/home/kwoodson/go/src/github.com/openshift/cluster-api-provider-alibaba":/go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud:Z -w /go/src/github.com/AliyunContainerService/cluster-api-provider-alibabacloud openshift/origin-release:golang-1.15 hack/goimports.sh .
> hack/verify-diff.sh
> diff --git a/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go b/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go
> index b3a352a2..38d9670b 100644
> --- a/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go
> +++ b/pkg/apis/alibabacloudprovider/v1beta1/zz_generated.deepcopy.go
> @@ -21,7 +21,7 @@ limitations under the License.
>  package v1beta1
>  
>  import (
> -	"k8s.io/api/core/v1"
> +	v1 "k8s.io/api/core/v1"
>  	"k8s.io/apimachinery/pkg/runtime"
>  )
>  
> make: *** [Makefile:135: goimports] Error 1
> ```
> 
> @menglingwei Can you also verify that the `make build` and other scripts produce the binaries? I was able to build with `podman build . `.

Ok. I have a try

**Comment by menglingwei** [comment]
> @menglingwei Were you able to drop the commit? Please let us know if we can assist. Thanks!

I'm working on it.If I can't solve it, I'll ask for your help. Thank you very much.

**Comment by menglingwei** [comment]
@JoelSpeed  I reset my branch,and force push it. And then i found the PR is closed. Is there something wrong with my operation？

**Comment by menglingwei** [comment]
> make generate

Sorry. I don't have a podman on my dev env.so i need to run it first.

**Comment by JoelSpeed** [comment]
The problem seems to be that the branch now doesn't share a common ancestor with our main branch. I want to make sure the two repositories are matched going forward so perhaps we need to reset our repo to match yours.

If you are confident that the branch is correct, I'd suggest you merge your branch into your main/master, once it's in your main, I can reset our repository to match yours, then we can make the openshift specific changes on top of that.

Let me check with @kwoodson and @elmiko on our side

**Comment by menglingwei** [comment]
> The problem seems to be that the branch now doesn't share a common ancestor with our main branch. I want to make sure the two repositories are matched going forward so perhaps we need to reset our repo to match yours.
> 
> If you are confident that the branch is correct, I'd suggest you merge your branch into your main/master, once it's in your main, I can reset our repository to match yours, then we can make the openshift specific changes on top of that.
> 
> Let me check with @kwoodson and @elmiko on our side

Yes. I already check my branch. and run make build in my local env.

**Comment by menglingwei** [comment]
> > The problem seems to be that the branch now doesn't share a common ancestor with our main branch. I want to make sure the two repositories are matched going forward so perhaps we need to reset our repo to match yours.
> > If you are confident that the branch is correct, I'd suggest you merge your branch into your main/master, once it's in your main, I can reset our repository to match yours, then we can make the openshift specific changes on top of that.
> > Let me check with @kwoodson and @elmiko on our side
> 
> �Yes. I already check my branch. and run make build in my local env.

I already merge into my main/master

**Comment by menglingwei** [comment]
perfect.

**Comment by menglingwei** [comment]
@JoelSpeed I see you've created a new branch.

**Comment by menglingwei** [comment]
@JoelSpeed  @elmiko  What are we going to do next? What do you need me to do?

**Comment by elmiko** [comment]
@menglingwei i think Kenny, Joel and myself need to sync up about the next steps.

**Comment by JoelSpeed** [comment]
So I was looking at the branch that we have today in the master of the Aliyun fork, it still has binaries in it because it was merged with the old verion.

What I've done is remove the old version in https://github.com/openshift/cluster-api-provider-alibaba/commits/sync-baba-ocp?before=6e39b84ab92b663a4bfa98e7fd1b68199a048faf+35&branch=sync-baba-ocp

So this branch is the one I'd prefer to merge to our master (it's all of your work on the current version, minus any binaries or history from the previous version). To make that work, and to be in sync, you will need to reset your master branch to https://github.com/openshift/cluster-api-provider-alibaba/commit/b0a0adfdf85e5c7a98b12cf865b48be578c0538d. Once that's done, we should have the same history apart from the final two commits we have added on top. This will allow us to automate rebasing in the future and pull in your changes.

Let me know if you have concerns about this or need further information to understand what I'm trying to achieve here :)

**Comment by menglingwei** [comment]
Have you finished the above work now? So I just need to reset our branch to [b0a0adf](https://github.com/openshift/cluster-api-provider-alibaba/commit/b0a0adfdf85e5c7a98b12cf865b48be578c0538d)

**Comment by JoelSpeed** [comment]
I think so yes, if you're happy to reset it to https://github.com/openshift/cluster-api-provider-alibaba/commit/b0a0adfdf85e5c7a98b12cf865b48be578c0538d then I think we can get our fork synced from there

**Comment by menglingwei** [comment]
> I think so yes, if you're happy to reset it to [b0a0adf](https://github.com/openshift/cluster-api-provider-alibaba/commit/b0a0adfdf85e5c7a98b12cf865b48be578c0538d) then I think we can get our fork synced from there

ok.  let me reset to [b0a0adf](https://github.com/openshift/cluster-api-provider-alibaba/commit/b0a0adfdf85e5c7a98b12cf865b48be578c0538d) . when i done it ,i will let you know.

**Comment by menglingwei** [comment]
@JoelSpeed  Now I'm looking at how to clean up the history files in .git and make package smaller.

**Comment by menglingwei** [comment]
I have updated repo https://github.com/AliyunContainerService/cluster-api-provider-alibabacloud

**Pull request closed without merging**
