### PR TITLE
Add a new Tag to identify which partner created the resource

### PR DESCRIPTION
**Pull request by menglingwei**

### CODE REVIEW

**Comment by menglingwei** [comment]
We want to identify that these resources are created through the Openshift platform.

**Comment by kwoodson** [comment]
@menglingwei Please rebase this PR. I have updated the `ResourceTagReference` to an `AlibabaResourceReference`. Thanks!

**Comment by kwoodson** [comment]
@menglingwei Please rebase using the latest changes.

**Comment by menglingwei** [comment]
> @menglingwei Please rebase using the latest changes.
go it.

**Comment by menglingwei** [comment]
@kwoodson  Any suggestion about this PR?

**Comment by kwoodson** [comment]
@menglingwei No suggestions but this PR should go together with github.com/openshift/installer/pull/5385. As soon as the installer merges we can merge this one.

**Comment by fabianofranz** [comment]
https://github.com/openshift/installer/pull/5385 is merged

/lgtm

**Comment by fabianofranz** [comment]
/assign @lobziik @Fedosin 

Mind taking a look and approving? Tks!

**Comment by kwoodson** [comment]
Tested this change along with #20. Everything looks good.
```
NAME                                 STATUS   ROLES    AGE     VERSION
test-kdlxs-master-0                  Ready    master   19m     v1.22.1+bac83a5
test-kdlxs-master-1                  Ready    master   20m     v1.22.1+bac83a5
test-kdlxs-master-2                  Ready    master   25s     v1.22.1+bac83a5
test-kdlxs-worker-us-east-1a-dqr7r   Ready    worker   7m38s   v1.22.1+bac83a5
test-kdlxs-worker-us-east-1b-rdkhq   Ready    worker   8m32s   v1.22.1+bac83a5
test-kdlxs-worker-us-east-1b-ttqsr   Ready    worker   8m10s   v1.22.1+bac83a5
NAME                                 PHASE     TYPE            REGION	   ZONE         AGE
test-kdlxs-master-0                  Running   ecs.g6.xlarge   us-east-1   us-east-1b   21m
test-kdlxs-master-1                  Running   ecs.g6.xlarge   us-east-1   us-east-1a   21m
test-kdlxs-master-2                  Running   ecs.g6.xlarge   us-east-1   us-east-1b   21m
test-kdlxs-worker-us-east-1a-dqr7r   Running   ecs.g6.large    us-east-1   us-east-1a   14m
test-kdlxs-worker-us-east-1b-rdkhq   Running   ecs.g6.large    us-east-1   us-east-1b   14m
```

**Pull request merged**
