### PR TITLE
drop bins commit,and reopen another PR

### PR DESCRIPTION
**Pull request by menglingwei**

### CODE REVIEW

**Comment by kwoodson** [comment]
@menglingwei @JoelSpeed @elmiko What is the status of this PR? We'd like to get this taken care of so that we can begin running the provider tests.

**Comment by elmiko** [comment]
i defer to @JoelSpeed 's guidance on this one, he had been chatting with @menglingwei about the removal. i _think_ we are good to merge this, but i'm not 100% sure.

**Comment by elmiko** [comment]
actually, scratch that, i think this comment is the most up to date info https://github.com/openshift/cluster-api-provider-alibaba/pull/1#issuecomment-900937477

**Comment by menglingwei** [comment]
> actually, scratch that, i think this comment is the most up to date info [#1 (comment)](https://github.com/openshift/cluster-api-provider-alibaba/pull/1#issuecomment-900937477)

Now I'm cleaning up the history files under.git to make them smaller. When I'm done, I'll push it to https://github.com/AliyunContainerService/cluster-api-provider-alibabacloud.  And then @JoelSpeed  will update the branch he forked from AliyunContainerService

**Pull request closed without merging**
